on: [push, pull_request]

name: CI

jobs:
  check_rust:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'ubuntu-22.04'
          - os: macos-latest
          - os: windows-latest
    name: "Check ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./src-tauri
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check
        run: cargo check

  test_rust:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: macos-latest
          - os: windows-latest
    name: "Test ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./src-tauri
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        run: cargo test

  lints_rust:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: macos-latest
          - os: windows-latest
    name: "Lint ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./src-tauri
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

  build_rust:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: macos-latest
          - os: windows-latest
    name: "Build ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./src-tauri
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo build
        run: cargo build

  format_rust:
    name: "Check formatting"
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./src-tauri
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Run fmt
        run: cargo fmt --check

  docs:
    name: "Build rust docs"
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./src-tauri
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Run fmt
        run: cargo doc
